service: distance-learning
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  tracing:
    apiGateway: true
    lambda: true # Optional, can be true (true equals 'Active'), 'Active' or 'PassThrough'
  logs:
    frameworkLambda: true

package:
  include:
    - ./src/**
  exclude:
    - .github/**
    - .vscode/**
    - diagrams/**
    - ./src/**/*.spec.js

functions:
  getHomework:
    handler: src/main.handler
    memorySize: 128
    description: Task to get the contents of an HTML Page and return links to files.
    tracing: Active
    environment:
      STORAGE_BUCKET_NAME:
        'Ref': HomeworkStorage
    events:
      - schedule:
          cron: 0 0 0 10 * ? *
          name: scheduled-fetch-n-parse
          description: Every weekday (except friday) at 10am
      - http:
          path: homework
          method: get
    destinations:
      onSuccess:
        'Ref': EmailNotify
      onFailure: 
        'Ref': EmailNotify

      #
      # TODO: Implement 'schedule' for event instead of http
      #
      # - schedule: rate(1 day) # TODO: Setup Time-based trigger (later)

resources:
  Resources:
    HomeworkStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
    EmailNotify:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
          - Endpoint: "ses@alexlapinski.name"
            Protocol: email
  Outputs:
    S3BucketName:
      Value: 
        'Fn::GetAtt': [HomeworkStorage, Arn]
      Description: S3 bucket holding the files downloaded from the daily fetcher.
      Export:
        Name: S3BucketName
    
