service: aws-nodejs # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs12.x

#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: main.handler
    events:
      - schedule: rate(1 day)