service: distance-learning
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: '*'
  tracing: true
  logs:
    frameworkLambda: true

package:
  include:
    - ./src/**
  exclude:
    - .github/**
    - .vscode/**
    - diagrams/**
    - ./src/**/*.spec.js

functions:
  getHomework:
    handler: src/main.handler
    memorySize: 1024
    description: Task to get the contents of an HTML Page and return links to files.
    tracing: Active
    environment:
      STORAGE_BUCKET_NAME:
        'Ref': HomeworkStorage
    events:
      - schedule:
          name: every-weekday-at-10am
          description: Every weekday (except friday) at 10am(EST)
          rate: cron(0 14 ? * 1,2,3,4 *)

resources:
  Resources:
    HomeworkStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
  Outputs:
    S3BucketName:
      Value: 
        'Fn::GetAtt': [HomeworkStorage, Arn]
      Description: S3 bucket holding the files downloaded from the daily fetcher.
      Export:
        Name: S3BucketName
    

plugins:
  - serverless-plugin-tracing
