service: distance-learning
provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    apiGateway: true
    lambda: true # Optional, can be true (true equals 'Active'), 'Active' or 'PassThrough'
  logs:
    frameworkLambda: true

package:
  include:
    - ./src/**

functions:
  getHomework:
    handler: main.handler
    tracing: Active
    environment:
      STORAGE_BUCKET_NAME:
        'Ref': HomeworkStorage
    events:
      - http:
        path: homework
        method: get
      #
      # TODO: Implement 'schedule' for event instead of http
      #
      # - schedule: rate(1 day) # TODO: Setup Time-based trigger (later)

resources:
  Resources:
    HomeworkStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
  Outputs:
    S3BucketName:
      Value: 
        'Fn::GetAtt': [HomeworkStorage, Arn]
      Description: S3 bucket holding the files downloaded from the daily fetcher.
      Export:
        Name: S3BucketName
    
